version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: "git submodule init && git submodule update --remote"
      - run: "./ci.sh"